# -*- coding: utf-8 -*-
"""Rifqi Mubarok_TechnicalAssessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVVldF-IdXgj4UeBmUlex5HmLbFyY8vE

# Proyek Analisis Sentimen
---

## "Analisis Sentimen Publik di Media Sosial X (Twitter) mengenai Pelemahan Nilai Tukar Rupiah terhadap Dolar Amerika Serikat"

---

## BAB 1: Pendahuluan


---
Perekonomian global akhir-akhir ini sedang tidak stabil, pemicunya datang dari berbagai krisis geopolitik dan dampak pasca pandemi yang membuat prospek ekonomi menjadi suram. Bank sentral negara maju seperti *The Fed* di Amerika Serikat mengambil langkah agresif untuk menaikkan suku bunga secara signifikan. Tren kenaikan suku bunga global ini secara langsung memberikan tekanan besar terhadap mata uang negara berkembang, termasuk Indonesia, yang memicu risiko pelemahan nilai tukar rupiah yang berkelanjutan.

Bank Indonesia (BI) berupaya keras menanggapi tekanan ini dengan menaikkan suku bunga acuan (BI Rate) untuk memperkuat nilai tukar rupiah dan menjaganya agar tidak menyentuh angka psikologis yang mengkhawatirkan, seperti Rp18.000 per dolar. Pelemahan rupiah memiliki dampak yang kompleks bagi perekonomian nasional, di satu sisi, hal ini meningkatkan biaya produksi dan menurunkan daya beli masyarakat, namun di sisi lain, depresiasi mata uang dapat memberikan keuntungan kompetitif bagi sektor ekspor karena barang dan jasa Indonesia menjadi lebih murah di pasar internasional.

Dalam menghadapi fenomena ini, media sosial X (Twitter) telah menjadi platform utama penyebaran informasi yang sangat cepat dan sering kali menjadi rujukan utama berita nasional. Dengan basis pengguna di Indonesia yang mencapai belasan hingga puluhan juta, X menjadi ruang bagi masyarakat untuk mengekspresikan opini, kritik, dan aspirasi masyarakat. Platform ini sering dianggap sebagai pendukung utama "kebebasan berbicara", yang menjadikannya indikator penting untuk mengukur pandangan publik nasional.Opini-opini yang terbentuk di platform ini mencerminkan persepsi kolektif masyarakat terhadap kondisi ekonomi yang sedang terjadi Oleh karena itu, riset analisis sentimen terhadap fenomena pelemahan rupiah ini menjadi sangat mendesak demi melihat bagaimana masyarakat mempersepsikan situasi ekonomi saat ini.

Jika dilihat dari aspek ekonomi, analisis ini berguna untuk melihat pengaruh pelemahan nilai tukar rupiah terhadap pembentukan sentimen pasar. Ketidakpastian informasi atau kepanikan digital di kalangan netizen dapat menciptakan spekulasi buruk yang merugikan iklim investasi, sekaligus memicu penurunan daya beli masyarakat akibat ketakutan akan inflasi. Di saat yang sama, fenomena ini berpengaruh juga pada aspek politik, di mana respons netizen menjadi alat ukur tingkat kepercayaan publik terhadap kesanggupan pemerintah dan otoritas moneter dalam menjaga stabilitas ekonomi nasional. Sentimen negatif yang ada di media sosial seharusnya dijadikan alarm dini atas ketidakpuasan publik terhadap kebijakan ekonomi yang sedang berjalan.

Selain itu, data yang diambil dari media sosial ini mampu memetakan aspek sosial berupa pola kecemasan atau perpecahan opini di masyarakat. Melalui analisis ini, dapat diuji secara objektif bagaimana masyarakat  yang terdampak langsung (seperti konsumen barang impor) merespons isu ini jika dibandingkan dengan kelompok yang cenderung diuntungkan (seperti pelaku komoditas ekspor atau pekerja domestik yang digaji dengan mata uang asing). Dan juga, penelitian ini berkaitan dengan budaya, khususnya dalam melihat budaya digital netizen Indonesia ketika menyikapi krisis ekonomi pada pelemahan nilai tukar rupiah ini. Melalui tren percakapan yang terkumpul, dapat dilihat bagaimana gaya masyarakat dalam menyampaikan kritik—apakah mereka cenderung menggunakan pendekatan satire/humor, gerakan edukasi finansial bersama, atau justru terjebak dalam kepanikan finansial.

---

## BAB 2: Rumusan Masalah

- Bagaimana distribusi dan tren volume sentimen publik (positif, negatif, dan netral) di platform X terhadap fenomena pelemahan nilai tukar rupiah terhadap dolar AS selama periode 2026?
- Topik atau klaster keluhan apa saja yang paling dominan memicu munculnya sentimen negatif netizen terkait terpuruknya nilai tukar rupiah?
- Bagaimana karakteristik dan pola narasi yang terkandung dalam sentimen positif dan netral di tengah isu pelemahan rupiah ini?

## BAB 3: Tujuan

- Mengidentifikasi distribusi dan tren volume sentimen publik secara berkala.
- Mengekstrak klaster keluhan dan topik utama yang mendasari sentimen negatif masyarakat
- Membedah karakteristik pola narasi edukatif dan suportif dalam sentimen positif serta netral

---

## BAB 4: Batasan Masalah


- **Cakupan data**: platform yang digunakan untuk pengambilan data hanya X (twitter), data yang dikumpulkan merupakan data tweet yang membahas tentang pelemahan nilai tukar rupiah terhadap dolar Amerika Serikat.
- **Rentang waktu**: periode pengambilan data (9 Maret- 26 Mei 2026).
- **Batasan geografis**: data tweet yang diambil hanya data yang 'mengandung' bahasa indonesia dan sesuai dengan kata kunci topik.
- **Batasan metodologis**:
Keterbatasan Model Sentimen Pre-trained
Model indonesian-roberta-base-sentiment-classifier dilatih pada dataset tertentu yang mungkin tidak sepenuhnya merepresentasikan bahasa informal, sarkasme, atau humor khas Twitter Indonesia. Selain itu, LDA Bersifat Interpretatif, topik yang dihasilkan oleh model LDA tidak memiliki label otomatis — penamaan topik dilakukan secara interpretatif oleh peneliti berdasarkan kata-kata dominan yang muncul.

---

## BAB 5: Kajian Pustaka / Referensi

LANDASAN TEORI

---
**Analisis Sentimen:** Analisis sentimen adalah sebuah teknik untuk mengidentifikasi perasaan, opini, emosi, yang diekspresikan dalam teks dalam kalimat/dokumen terhadap berbagau entitas seperti produk, layanan dan isu. [Sumber.](https://ejurnal.snn-media.com/index.php/jics/article/view/24)

**Topic Modeling:** Topic Modeling berfungsi untuk mengidentifikasi dan mempelajari topik-topik dalam dokumen serta mengelompokkan kata-kata yang berhubungan terhadap topik khusus.
[Sumber.](https://j-ptiik.ub.ac.id/index.php/j-ptiik/article/view/14540)

**World Cloud:** Word Cloud adalah gambaran visual berdasarkan frekuensi kemunculan kata-kata pada suatu kumpulan teks, dimana ukuran huruf menentukan frekuensi kemunculan sebuah kata yang artinya semakin besar ukuran huruf maka semakin besar kemunculan kata tersebut dan sebaliknya. [Sumber.](https://share.google/4vsuAOEdFHD3DFUtG)

**Case Folding:** Case folding merupakan suatu tahapan proses untuk mengubah kata menjadi bentuk yang
sama menggunakan Python string lower method dengan tujuan untuk
mengembalikan semua kata kedalam bentuk huruf kecil semua supaya data text yang diproses
semuanya dalam kondisi bentuk yang sama. [Sumber.](https://share.google/0cNy3tBVVo1cn1Azu)

**Tokenizing:** Tokenizing adalah proses memecah kalimat menjadi kata-kata (token) yang dilakukan
untuk menjadikan sebuah kalimat menjadi lebih bermakna. [Sumber.](https://share.google/ZSisf4jVqeYVCYuQE)

**StopWords:** StopWords adalah tahap mengambil kata-kata penting dari hasil token. Algoritma
stoplist (membuang kata yang kurang penting) atau wordlist (menyimpan kata yang
penting) dapat digunakan pada tahap ini. [Sumber.](https://share.google/ZSisf4jVqeYVCYuQE)

**Stemming:** Stemming adalah proses mengembalikan kata
kedalam bentuk dasar. Jika stemming berhasil dilakukan maka akan menghasilkan klasifikasi
sentimen yang akurat. [Sumber.](https://share.google/KKTZwWFFK9YUpvfTK)

---

**Library Python:** Pandas, Matplotlib.pyplot, Numpy, Scipy.stats, Seaborn, RE (Regular Expression), NLTK (Natural Language Toolkit), Sastrawi, Torch, Scikit-learn.

----

**Kenaikan Suku bunga Amerika Serikat:** [Sumber.](https://fsi.stanford.edu/sipr/global-implications-feds-rate-hikes)

**Pelemahan nilai tukar rupiah terhadap dolar tahun 2026:** [Sumber.](https://www.bbc.com/indonesia/articles/c5y9eexrq9zo)

## BAB 6: Hasil dan Pembahasan

### 6.1 Pengumpulan Data (Data Collection)

**Sumber Data:** Data yang saya ambil merupakan data sentimen yang berasal dari X (twitter) dengan topik yang diambil untuk analisis sentimen pada "Pelemahan nilai tukar rupiah".

**Metode Pengumpulan Data:** Metode yang saya gunakan menggunakan platform pihak ke-3 yaitu [Console Apify](https://console.apify.com/actors/CJdippxWmn9uRfooo/input), ini adalah antarmuka berbasis cloud yang berfungsi untuk melakukan web scraping secara otomatis, adapun jenis manajemen (Actor) yang saya gunakan yaitu "kaitoeasyapi 0.25 dolar/1k tweets", dengan memanfaatkan 5 dolar gratis yang diberikan selama 1 bulan, saya dapat mengambil data sebanyak 25k data dengan menggunakan 2 API / 2 akun berbeda.

**NOTE:** Kode yang saya buat dibawah ini dijalankan melalui aplikasi "Visual Studio Code", data berhasil terkumpul sebanyak 25.019 data.

Jadi saya hanya mencantumkannya saja di google colab ini,
anda bisa mencobanya dengan cara mengganti API client pada "client = ApifyClient("ISI DENGAN API APIFY ANDA")".
"""

# !pip install apify-client pandas

# !pip install openpyxl

# from apify_client import ApifyClient
# import pandas as pd
# # Initialize the ApifyClient with your API token
# client = ApifyClient("API ANDA")

# # Prepare the Actor input
# run_input = {
#     "filter:blue_verified": False,
#     "filter:consumer_video": False,
#     "filter:has_engagement": False,
#     "filter:hashtags": False,
#     "filter:images": False,
#     "filter:links": False,
#     "filter:media": False,
#     "filter:mentions": False,
#     "filter:native_video": False,
#     "filter:nativeretweets": False,
#     "filter:news": False,
#     "filter:pro_video": False,
#     "filter:quote": False,
#     "filter:replies": False,
#     "filter:safe": False,
#     "filter:spaces": False,
#     "filter:twimg": False,
#     "filter:videos": False,
#     "filter:vine": False,
#     "from": "elonmusk",
#     "include:nativeretweets": False,
#     "lang": "in",
#     "maxItems": 25000,
#     "searchTerms": [
#         "(rupiah OR dolar OR usd OR kurs) (\"melemah\" OR \"anjlok\" OR \"terpuruk\" OR \"tembus\" OR \"ambles\" OR \"inflasi\" ) since:2025-01-01 until:2026-05-27"
#     ]
# }

# # Run the Actor and wait for it to finish
# run = client.actor("CJdippxWmn9uRfooo").call(run_input=run_input)

# # Fetch and print Actor results from the run's dataset (if there are any)
# items = []
# for item in client.dataset(run.default_dataset_id).iterate_items():
#     print(item)
#     items.append(item)

# df = pd.DataFrame(items)
# df.to_excel("PelemahanRupiah_25k.xlsx", index=False)
# df

"""### Berikut adalah data yang telah berhasil dikumpulkan"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/PelemahanRupiah_25k.csv', delimiter=';')
df

"""### 6.2 Pembersihan Data (Data Cleaning) & Penilaian Kualitas Data

*Dokumentasikan proses pembersihan data yang dilakukan: handling missing values, deduplikasi, normalisasi teks, penghapusan noise, dll. Sertakan pula penilaian terhadap kualitas data awal.*
"""

df.info()

"""Dapat dilihat bahwa dataframe ini memiliki 31 kolom dan 25.019 baris data yang memiliki tipe data yang berbeda-beda. Kolom pada dataframe ini tidak akan digunakan semua, kolom-kolom yang tidak akan digunakan untuk analisis pada penelitian ini akan dihapus, supaya pada saat dilakukan pemodelan tidak mengalami error atau menghasilkan output yang tidak seharusnya diinginkan.

### Coloumn Selection

Tujuan dari seleksi kolom ini adalah untuk menyeleksi kolom yang tidak digunakan untuk analisis namun ada pada dataset.
"""

# Seleksi Kolom
# Kolom yang akan digunakan untuk analisis
kolom_pilihan = ['id', 'url', 'text', 'createdAt', 'likeCount', 'retweetCount', 'replyCount', 'viewCount', 'lang']

# Filter dataframe
df_analisis = df[kolom_pilihan]

"""Dari keseluruhan kolom yang tersedia pada dataset mentah, hanya 9 kolom yang dipilih
untuk keperluan analisis. Pemilihan ini didasarkan pada relevansi dan fungsi masing-masing
kolom terhadap tujuan penelitian, yaitu:

- **id** — Identitas unik setiap tweet, digunakan untuk memastikan tidak ada data duplikat.
- **url** — Tautan tweet asli, berguna untuk verifikasi dan keterlacakan sumber data.
- **text** — Konten utama tweet yang menjadi objek analisis sentimen dan teks.
- **createdAt** — Waktu publikasi tweet, digunakan untuk analisis tren temporal
  (volume diskusi dari waktu ke waktu).
- **likeCount, retweetCount, replyCount, viewCount** — Metrik engagement yang
  mencerminkan tingkat resonansi sebuah tweet di publik. Tweet dengan engagement tinggi
  berpotensi memiliki pengaruh lebih besar terhadap pembentukan opini masyarakat.
- **lang** — Kode bahasa tweet, digunakan untuk memfilter konten berbahasa Indonesia
  agar analisis tetap relevan dengan konteks lokal.

Kolom-kolom lain yang tidak dipilih (seperti metadata akun, koordinat lokasi, atau
informasi media) dianggap tidak relevan dengan fokus analisis sentimen berbasis teks
pada penelitian ini, sehingga dihilangkan untuk menjaga efisiensi pemrosesan data.

### Missing Value
"""

df_analisis.info()

missing_values_per_column = df_analisis.isnull().sum()

print("jumlah missing values per kolom")
print(missing_values_per_column)

"""Hasil pengecekan missing value menunjukkan bahwa seluruh 9 kolom yang dipilih
memiliki nilai **0 missing value** dari total 25.019 entri data. Hal ini mengindikasikan
bahwa data yang berhasil dikumpulkan melalui proses scraping sudah lengkap dan tidak
memerlukan penanganan missing value seperti imputasi atau penghapusan baris.

Kondisi ini cukup ideal untuk analisis sentimen, karena kolom utama yang menjadi
objek analisis yaitu **text** dipastikan terisi penuh di seluruh baris data, sehingga
tidak ada risiko kehilangan sampel pada tahap pemrosesan teks selanjutnya.

### Duplicated Data
"""

df_analisis.duplicated().value_counts()

"""Tidak terdapat data duplikat pada data mentah yang telah dikumpulkan, dapat dilihat bahwa "False = 25019", artinya tidak ada data duplikat.

Hal ini wajar mengingat setiap tweet memiliki **id** yang unik, dan proses scraping
melalui Apify sudah menangani deduplikasi secara otomatis pada level platform.
"""

df_analisis = df_analisis.drop_duplicates()
print("Jumlah data setelah menghapus data duplikat:", df_analisis.shape)

"""Meskipun tidak ditemukan duplikat, fungsi **drop_duplicates()** tetap dijalankan
sebagai langkah preventif untuk memastikan konsistensi data, terbukti dari output
yang menunjukkan jumlah baris tetap **25.019 baris dengan 9 kolom** setelah proses
ini dijalankan.

### Change Data Type "createdAt"
Tipe data pada kolom "createdAt" saat ini berupa tipe data object, saya akan menggantinya menjadi tipe data datetime
"""

df_analisis['createdAt'] = pd.to_datetime(df_analisis['createdAt'])
display(df_analisis.info())

"""Tujuan dari pergantian tipe data dari object ke datetime adalah untuk memudahkan visualisasi data pada analisis yang memerlukan kolom createdAt.

### Filtering Language
"""

print("Jumlah tweet per bahasa sebelum penghapusan:")
lang_counts_before = df_analisis['lang'].value_counts()
display(lang_counts_before)

other_lang_counts = lang_counts_before[lang_counts_before.index != 'in']
print(other_lang_counts.sum())

df_analisis = df_analisis[df_analisis['lang'] == 'in']
print("Jumlah data setelah menghapus tweet selain berbahasa Indonesia:", df_analisis.shape)
display(df_analisis['lang'].value_counts())

"""Dari proses identifikasi bahasa menggunakan atribut lang, diperoleh 25.019 tweet dengan mayoritas menggunakan bahasa Indonesia sebanyak 24.910 tweet (99,56%). Untuk menjaga konsistensi analisis sentimen, dilakukan proses filtering dengan hanya mempertahankan tweet berbahasa Indonesia (lang='in'). Hasil filtering menghasilkan 24.910 tweet yang siap digunakan pada tahap preprocessing selanjutnya, sedangkan 109 tweet berbahasa selain Indonesia dihapus dari dataset penelitian.

### Case Folding

Case Folding digunakan untuk mengubah semua huruf menjadi huruf kecil dan menghapus angka, tanda baca, hastag, nomor, emoji, whitespace dan URL.
"""

import re

# Compile emoji
EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emoticon
    "\U0001F300-\U0001F5FF"  # simbol & gambar
    "\U0001F680-\U0001F6FF"  # simbol transportasi & peta
    "\U0001F1E0-\U0001F1FF"  # bendera (iOS)
    "\U00002702-\U000027B0"  # Dingbat
    "\U000024C2-\U0001F251"  # Huruf dalam kurung dan simbol-simbol lainnya
    "]+",
    flags=re.UNICODE
)

def clean_text(text):
    text = text.lower() # Lowercasing (Mengubah huruf besar menjadi huruf kecil)
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE) # Hapus URL
    text = re.sub(r'@\w+', '', text) # Hapus mention
    text = re.sub(r'#\w+', '', text) # Hapus hashtag
    text = EMOJI_PATTERN.sub(r'', text) # Hapus emoji dengan (compiled pattern)
    text = re.sub(r'[\d+\.\!\?\,\;\:"\)\(/\[\]\\-]+', '', text) # Hapus tanda baca dan angka
    text = re.sub(r'\s+', ' ', text).strip() # Hapus spasi kosong yang berlebihan
    return text

df_analisis['text_clean'] = df_analisis['text'].apply(clean_text)
display(df_analisis[['text', 'text_clean']].head())

"""Tahap case folding mengubah seluruh karakter huruf menjadi huruf kecil (*lowercase*) untuk menyeragamkan bentuk kata. Selain itu, dilakukan juga pembersihan teks dengan menghapus URL, mention, hashtag, emoji, angka, dan tanda baca yang tidak diperlukan.

### Tokenizing dan Stopwords Removal

**Tokenizing:** Memecah kalimat menjadi kata-kata tunggal (token).

**Stopword Removal:** Menghapus kata-kata sambung atau kata yang tidak memiliki makna penting dalam analisis
"""

import nltk
from nltk.corpus import stopwords

# Download data NLTK yang diperlukan
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords', quiet=True)

# Kombinasikan Stopword english dan bahasa indonesia
english_stopwords = set(stopwords.words('english'))
indonesian_stopwords = set(stopwords.words('indonesian'))
custom_stopwords = {
    'yg', 'rp', 'aja', 'ga', 'ya', 'gak', 'nya', 'utk',
    'dgn', 'jg', 'sy', 'krn', 'tdk', 'tp', 'org',
    'udah', 'sdh', 'itu', 'ini', 'ada', 'juga', 'bisa',
    'kalo', 'kalau', 'gimana', 'emang', 'kayak', 'banget',
    'dong', 'sih', 'deh', 'loh', 'kan', 'nih', 'tuh'
}
all_stopwords = english_stopwords.union(indonesian_stopwords).union(custom_stopwords)

def tokenize_and_remove_stopwords(text):
    if pd.isna(text): # Handle nilai NaN jika ada
        return ""
    tokens = text.split() # Tokenisasi sederhana dengan memisahkan berdasarkan spasi
    filtered_tokens = [word for word in tokens if word not in all_stopwords and len(word) > 1] # Hapus kata-kata pengisi dan kata-kata yang terdiri dari satu karakter
    return ' '.join(filtered_tokens)

df_analisis['text_processed'] = df_analisis['text_clean'].apply(tokenize_and_remove_stopwords)
display(df_analisis[['text', 'text_clean', 'text_processed']].head())

"""Di tahap ini dilakukan tokenisasi dengan memecah teks menjadi kumpulan kata berdasarkan spasi. Selanjutnya dilakukan stopword removal menggunakan kombinasi stopword Bahasa Indonesia dan Bahasa Inggris dari NLTK serta stopword tambahan yang disesuaikan dengan karakteristik bahasa informal pada media sosial X (Twitter). Tujuannya menghilangkan kata-kata umum yang tidak memiliki penting terhadap penentuan sentimen sehingga hanya tersisa kata-kata yang lebih representatif untuk proses analisis sentimen.

### Stemming

Stemming merupakan proses pengurangan
imbuhan dalam kata-kata ke bentuk dasarnya
sehingga membantu dalam pre-processing teks, kata,
dan dokumen untuk normalisasi teks.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install Sastrawi
# 
# import Sastrawi
# from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
# 
# # Create stemmer
# factory = StemmerFactory()
# stemmer = factory.create_stemmer()
# 
# def stem_text(text):
#     if pd.isna(text):
#         return ""
#     return stemmer.stem(text)
# 
# df_analisis['text_stemmed'] = df_analisis['text_processed'].apply(stem_text)

display(df_analisis[['text', 'text_clean', 'text_processed', 'text_stemmed']].head())

"""Proses stemming menggunakan library Sastrawi berhasil merubah kata ke bentuk dasarnya — misalnya "melemahkan", "pelemahan", dan "dilemahkan" seluruhnya menjadi satu token tunggal "lemah". Perubahan ini krusial untuk memastikan bahwa kata-kata yang secara identik tidak dihitung sebagai entitas terpisah dalam analisis frekuensi dan pemodelan topik.
Namun terdapat batasan metodologis: Sastrawi dirancang untuk bahasa Indonesia formal, sehingga kata-kata gaul khas Twitter seperti "anjlok", "gw", atau "bgt" tidak mengalami stemming yang bermakna dan tetap dipertahankan dalam bentuk aslinya — yang justru menjadi keuntungan karena nuansa informal tersebut tetap terjaga untuk keperluan analisis emosi dan sentimen.

### Kualitas data
"""

# Menilai kualitas data setelah dilakukan data preprocessing

nilai_awal = len(df)
nilai_awal_kolom = df.shape[1]
nilai_setelah_cleaning = len(df_analisis)
nilai_setelah_cleaning_kolom = df_analisis.shape[1]
persentase_bersih = (nilai_setelah_cleaning / nilai_awal) * 100

print(f"Jumlah baris awal: {nilai_awal}")
print(f"Jumlah kolom awal: {nilai_awal_kolom}")
print(f"Jumlah baris setelah cleaning: {nilai_setelah_cleaning}")
print(f"Jumlah kolom setelah cleaning: {nilai_setelah_cleaning_kolom}")
print(f"Persentase data bersih (berdasarkan baris): {persentase_bersih:.2f}%")

"""Proses pembersihan data menghasilkan dataset yang sangat bersih dengan tingkat retensi **99,56%** dari data mentah awal — hanya 109 tweet (0,44%) yang dieliminasi karena bukan berbahasa Indonesia. Tidak ditemukan satupun missing value maupun data duplikat, yang mencerminkan kualitas proses scraping yang solid.


Tahapan preprocessing teks — mulai dari case folding, penghapusan URL/mention/hashtag/emoji, tokenizing, stopword removal (gabungan kosakata Bahasa Indonesia, Inggris, dan bahasa gaul media sosial), hingga stemming menggunakan Sastrawi — merupakan pipeline yang tepat untuk karakteristik bahasa informal Twitter Indonesia. Bahasa gaul khas netizen seperti "yg", "gak", "banget", dan "dong" dimasukkan ke dalam custom stopwords, menunjukkan bahwa teks Twitter jauh berbeda dari teks formal berita.


Hasil akhir menghasilkan **24.910 baris** data bersih dengan **12 kolom** yang siap dianalisis — dari 31 kolom mentah yang ada di dataset awal, hanya 9 kolom relevan yang dipertahankan, lalu diperkaya menjadi 12 setelah proses analisis.

### 6.3 Exploratory Data Analysis (EDA)

*Lakukan eksplorasi data untuk memahami karakteristik dataset. Visualisasikan distribusi, tren, dan pola yang menarik sebelum masuk ke analisis sentimen.*
"""

df_analisis.describe()

"""### 1. Temporal Analysis: Volume Tweet dari Waktu ke Waktu"""

import matplotlib.pyplot as plt
import seaborn as sns

df_analisis['tanggal'] = df_analisis['createdAt'].dt.date
daily_tweet_counts = df_analisis.groupby('tanggal').size().reset_index(name='hitung_tweet')

plt.figure(figsize=(12, 6))
sns.lineplot(x='tanggal', y='hitung_tweet', data=daily_tweet_counts)
plt.title(' Volume Tweet dari Waktu ke Waktu')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah Tweet')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""Analisis temporal menjadi salah satu temuan paling informatif dalam riset ini. Grafik volume tweet dari waktu ke waktu bukan sekadar garis naik-turun biasa — ia adalah barometer digital yang merekam momen-momen ketika publik paling terpukul oleh berita ekonomi. Lonjakan volume tweet yang tajam sangat mungkin berkorelasi dengan beberapa peristiwa pemicu (trigger events) yang terjadi selama periode penelitian: ketika rupiah pertama kali menembus Rp17.000, saat Bank Indonesia mengumumkan kenaikan BI Rate darurat sebesar 50 basis poin menjadi 5,25% pada 19–20 Mei 2026, atau ketika rupiah nyaris menembus Rp17.900 pada akhir Mei. Pola lonjakan ini menggambarkan bahwa publik Indonesia tidak pasif — mereka reaktif secara digital terhadap setiap guncangan ekonomi yang mereka rasakan dalam kehidupan sehari-hari.

### 2. Distribusi Metrik Engagement
"""

engagement_cols = ['likeCount', 'retweetCount', 'replyCount', 'viewCount']

plt.figure(figsize=(16, 10))
for i, col in enumerate(engagement_cols):
    plt.subplot(2, 2, i + 1)
    sns.histplot(df_analisis[col], bins=50, kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.yscale('log')
plt.tight_layout()
plt.show()

"""Distribusi metrik engagement (likes, retweet, reply, views) yang menunjukkan pola right-skewed ekstrem adalah temuan yang selaras dengan hukum distribusi kekuatan (power law) di media sosial. Artinya, sebagian sangat kecil tweet berhasil menjangkau jutaan pengguna — kemungkinan besar tweet dari tokoh publik, jurnalis ekonomi, atau akun influencer finansial yang membahas pelemahan rupiah. Tweet-tweet viral ini memiliki dampak pembentukan opini yang jauh lebih besar dari ribuan tweet biasa, dan ini menjadi catatan penting: sentimen yang muncul di dataset tidak sepenuhnya mencerminkan distribusi opini yang setara, melainkan juga dipengaruhi oleh amplifikasi dari akun-akun berpengaruh.

### 3. Analisis Konten: Kata-kata yang Paling Sering Digunakan
"""

from collections import Counter
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

# Menggabungkan semua teks yang telah dibersihkan menjadi satu string
all_words = ' '.join(df_analisis['text_clean']).split()

# Hapus kata-kata pengisi umum dalam bahasa Inggris dan bahasa Indonesia
# Dengan asumsi bahwa ‘in’ adalah kata dalam bahasa Indonesia berdasarkan analisis sebelumnya
english_stopwords = set(stopwords.words('english'))
indonesian_stopwords = set(stopwords.words('indonesian'))

# Menambahkan kata-kata penghalang yang spesifik untuk domain tertentu secara manual jika ‘in’ bukanlah istilah standar dalam bahasa Indonesia atau jika dataset tersebut mengandung istilah teknis tertentu.

# Saring wordstop dan kata-kata yang terdiri dari satu karakter
filtered_words = [word for word in all_words if word not in english_stopwords and word not in indonesian_stopwords and len(word) > 1]

# Mengambil 20 kata yang paling umum
common_words = Counter(filtered_words).most_common(20)

# Mengonversi ke DataFrame untuk visualisasi
common_words_df = pd.DataFrame(common_words, columns=['word', 'count'])

plt.figure(figsize=(12, 7))
sns.barplot(x='count', y='word', data=common_words_df)
plt.title('20 Kata Paling Sering Digunakan dalam Tweet')
plt.xlabel('Jumlah')
plt.ylabel('Kata')
plt.tight_layout()
plt.show()

"""Analisis frekuensi kata mengungkap vocabulari krisis yang digunakan publik Indonesia ketika membicarakan pelemahan rupiah. Kemunculan kata-kata seperti "melemah", "anjlok", "dolar", "impor", dan "inflasi" sebagai kata dominan mencerminkan kesadaran publik yang cukup tinggi terhadap mekanisme transmisi ekonomi — bahwa pelemahan rupiah berimplikasi langsung pada harga barang impor dan inflasi.

### 4. Content Analysis: N-gram Analysis (Common Phrases)
"""

from nltk.util import ngrams
from collections import Counter

# Combine all stemmed text into a single string for N-gram analysis
all_stemmed_text_for_ngrams = ' '.join(df_analisis['text_stemmed'].dropna())

# Tokenize the stemmed text
tokenized_stemmed_words = all_stemmed_text_for_ngrams.split()

# Generate bigrams (2-word phrases)
bigrams_stemmed = list(ngrams(tokenized_stemmed_words, 2))
common_bigrams_stemmed = Counter(bigrams_stemmed).most_common(20)

# Convert to DataFrame for visualization
common_bigrams_stemmed_df = pd.DataFrame([(' '.join(word), count) for word, count in common_bigrams_stemmed], columns=['bigram', 'count'])

plt.figure(figsize=(12, 7))
sns.barplot(x='count', y='bigram', data=common_bigrams_stemmed_df)
plt.title('20 Most Common Stemmed Bigrams in Tweets')
plt.xlabel('Count')
plt.ylabel('Bigram')
plt.tight_layout()
plt.show()

# Generate trigrams (3-word phrases)
trigrams_stemmed = list(ngrams(tokenized_stemmed_words, 3))
common_trigrams_stemmed = Counter(trigrams_stemmed).most_common(20)

# Convert to DataFrame for visualization
common_trigrams_stemmed_df = pd.DataFrame([(' '.join(word), count) for word, count in common_trigrams_stemmed], columns=['trigram', 'count'])

plt.figure(figsize=(12, 7))
sns.barplot(x='count', y='trigram', data=common_trigrams_stemmed_df)
plt.title('20 Most Common Stemmed Trigrams in Tweets')
plt.xlabel('Count')
plt.ylabel('Trigram')
plt.tight_layout()
plt.show()

"""Bigram dan trigram yang muncul kemungkinan besar mencakup frasa-frasa seperti "rupiah melemah", "harga naik", "daya beli turun", atau "Bank Indonesia", yang menggambarkan bagaimana publik menghubungkan fenomena nilai tukar dengan dampaknya pada kehidupan sehari-hari.

### 5. Panjang Teks tweet
"""

df_analisis = df_analisis.copy()
df_analisis['text_length'] = df_analisis['text_clean'].apply(lambda x: len(x.split()))

# Cell EDA (sebelum sentimen) — hanya histogram
df_analisis = df_analisis.copy()
df_analisis['text_length'] = df_analisis['text_clean'].apply(lambda x: len(x.split()))

plt.figure(figsize=(8, 6))
sns.histplot(df_analisis['text_length'], bins=40, kde=True, color='steelblue')
plt.title('Distribusi Panjang Tweet (Jumlah Kata)')
plt.xlabel('Jumlah Kata')
plt.ylabel('Frekuensi')
plt.axvline(df_analisis['text_length'].mean(), color='red', linestyle='--', label=f"Mean: {df_analisis['text_length'].mean():.1f}")
plt.axvline(df_analisis['text_length'].median(), color='green', linestyle='--', label=f"Median: {df_analisis['text_length'].median():.1f}")
plt.legend()
plt.tight_layout()
plt.show()

df_analisis = df_analisis.copy()
df_analisis['text_length'] = df_analisis['text_clean'].apply(lambda x: len(x.split()))

plt.figure(figsize=(10, 6))
sns.histplot(df_analisis['text_length'], bins=50, kde=True, color='steelblue')

# Garis mean dan median
plt.axvline(df_analisis['text_length'].mean(), color='red', linestyle='--',
            label=f"Mean: {df_analisis['text_length'].mean():.1f}")
plt.axvline(df_analisis['text_length'].median(), color='green', linestyle='--',
            label=f"Median: {df_analisis['text_length'].median():.1f}")

plt.title('Distribusi Panjang Tweet (Jumlah Kata)')
plt.xlabel('Jumlah Kata')
plt.ylabel('Frekuensi')
plt.xlim(0, 200)
plt.legend()
plt.tight_layout()
plt.show()

"""Pola distribusi panjang tweet dengan median 20 kata dan mean 37,5 kata menunjukkan dua tipe pemosting yang dominan di dataset ini: kelompok pertama adalah publik umum yang bereaksi cepat dengan komentar pendek dan emosional ("Rupiah anjlok lagi sih, mau beli barang impor makin susah"), dan kelompok kedua adalah kelompok yang lebih analitis — mungkin ekonom amatir, mahasiswa ekonomi, atau pegiat finansial — yang menulis thread atau cuitan panjang berisi penjelasan dan analisis. Rata-rata yang jauh di atas median (37,5 vs 20 kata) mengindikasikan bahwa meski sebagian besar reaksi bersifat singkat dan emosional, ada segmen populasi yang merespons dengan wacana yang lebih substansial dan edukatif.

### 6.4 Analisis Sentimen & Metode Tambahan

*Terapkan analisis sentimen menggunakan pre-trained model dan setidaknya satu metode tambahan (Topic Modeling, Word Cloud, atau Emotion Analysis). Dokumentasikan hasilnya.*

### Pre-trained model
"""

from transformers import pipeline
import torch

sentiment_model_loaded = False
try:
    # Load a publicly available pre-trained Indonesian sentiment analysis model
    sentiment_pipeline = pipeline(
        'sentiment-analysis',
        model='w11wo/indonesian-roberta-base-sentiment-classifier',
        tokenizer='w11wo/indonesian-roberta-base-sentiment-classifier',
        device=0 if torch.cuda.is_available() else -1 # Use GPU if available
    )
    sentiment_model_loaded = True
    print("Model sentimen berhasil dimuat: w11wo/indonesian-roberta-base-sentiment-classifier")
except Exception as e:
    print(f"Gagal memuat model sentimen: {e}")
    print("Analisis sentimen akan dilewati karena masalah otorisasi/akses model atau model tidak ditemukan.")

if sentiment_model_loaded:
    # Define a function to get sentiment, handling potential NaN values
    def get_sentiment(text):
        if pd.notna(text):
            # Apply sentiment analysis, truncating long texts to prevent errors
            result = sentiment_pipeline(text, truncation=True, max_length=512)[0]
            return result['label'], result['score']
        return None, None

    # Apply the function to 'text_stemmed' column and create new 'sentimen' and 'skor_sentimen' columns
    # Using .loc to avoid SettingWithCopyWarning if df_analisis is a slice
    df_analisis[['sentimen', 'skor_sentimen']] = df_analisis['text_clean'].apply(lambda x: pd.Series(get_sentiment(x)))

    # Tampilkan distribusi sentimen
    print("\nDistribusi Sentimen:")
    sentiment_counts = df_analisis['sentimen'].value_counts(dropna=False)
    print(sentiment_counts)

    # Visualisasi distribusi sentimen
    plt.figure(figsize=(8, 6))
    sns.barplot(x=sentiment_counts.index, y=sentiment_counts.values, palette='coolwarm')
    plt.title('Distribusi Sentimen')
    plt.xlabel('Sentimen')
    plt.ylabel('Jumlah Tweet')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

    print("\nContoh data dengan sentimen:")
    display(df_analisis[['text_stemmed', 'sentimen', 'skor_sentimen']].head())
else:
    print("Kolom 'sentimen' dan 'skor_sentimen' tidak dibuat karena model gagal dimuat.")

print("\nAnalisis Sentimen Selesai.")

"""Hasil klasifikasi sentimen menggunakan model pre-trained w11wo/indonesian-roberta-base-sentiment-classifier mengungkap gambaran yang tidak mengejutkan namun tetap signifikan: sentimen **negatif mendominasi** percakapan publik tentang pelemahan rupiah. Ini adalah respons yang rasional dan manusiawi. Ketika rupiah melemah dari Rp16.675 di awal Januari 2026 menjadi hampir Rp17.900 pada akhir Mei — atau setara pelemahan lebih dari 7% dalam lima bulan — dampaknya bukan abstrak bagi mayoritas masyarakat Indonesia. Menurut ekonom CORE, depresiasi rupiah sebesar 10% berpotensi mendongkrak inflasi 1,5 hingga 2,5 poin persentase. Rumah tangga dengan pengeluaran Rp2–3 juta per bulan bisa kehilangan daya beli riil 3–5% hanya dalam beberapa bulan. Keluhan di Twitter dengan demikian bukan sekadar pelampiasan emosi — ia adalah sinyal kesulitan ekonomi nyata yang dialami jutaan orang.


Yang menarik untuk dicermati adalah porsi sentimen **positif dan netral** yang tetap ada. Kehadiran sentimen positif kemungkinan berasal dari dua segmen: (1) pelaku ekspor dan penerima remitansi yang justru diuntungkan oleh pelemahan rupiah, serta (2) kelompok "kontranarasi" yang mencoba menenangkan panik dengan narasi edukatif atau optimistis. Sementara sentimen netral mencerminkan tweet yang bersifat informatif — berbagi berita, data kurs, atau analisis tanpa muatan emosional yang kuat.

### Topic Modeling
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from nltk.corpus import stopwords

# Ensure stopwords are downloaded
try:
    nltk.data.find('corpora/stopwords')
except nltk.downloader.DownloadError:
    nltk.download('stopwords', quiet=True)

english_stopwords = set(stopwords.words('english'))
indonesian_stopwords = set(stopwords.words('indonesian'))
all_stopwords = english_stopwords.union(indonesian_stopwords)

sentiments = df_analisis['sentimen'].unique()

for sentiment_label in sentiments:
    if pd.notna(sentiment_label): # Skip NaN sentiments if any
        print(f"\n--- Topic Modeling for {sentiment_label.capitalize()} Sentiment ---")

        # Filter DataFrame for the current sentiment and drop NaNs from text_stemmed
        sentiment_df = df_analisis[df_analisis['sentimen'] == sentiment_label]
        corpus_sentiment = sentiment_df['text_stemmed'].dropna().tolist()

        if len(corpus_sentiment) < 2: # LDA needs at least 2 documents
            print(f"Tidak cukup data teks bersih untuk sentimen: {sentiment_label} ({len(corpus_sentiment)} dokumen). Melewati.")
            continue

        # Use CountVectorizer to create Document-Term Matrix (DTM)
        vectorizer = CountVectorizer(
            max_df=0.85, # ignore words that appear in 85% or more of documents
            min_df=2,    # ignore words that appear in less than 2 documents
            stop_words=list(all_stopwords)
        )

        try:
            dtm = vectorizer.fit_transform(corpus_sentiment)
        except ValueError as e:
            print(f"Tidak dapat membuat DTM untuk sentimen {sentiment_label}: {e}. Mungkin terlalu sedikit kata unik setelah stopword removal.")
            continue

        # Initialize and apply Latent Dirichlet Allocation (LDA)
        # Number of components (topics) can be adjusted. Start with 5 topics.
        n_components = min(5, dtm.shape[0] - 1) # Ensure n_components is less than number of documents
        if n_components < 2:
            print(f"Tidak cukup dokumen atau kata unik untuk membuat {n_components} topik untuk sentimen {sentiment_label}. Melewati.")
            continue

        lda = LatentDirichletAllocation(n_components=n_components, random_state=42)
        lda.fit(dtm)

        # Display top words for each topic
        feature_names = vectorizer.get_feature_names_out()
        for idx, topic in enumerate(lda.components_):
            top_words_idx = topic.argsort()[:-10-1:-1] # Get indices of top 10 words
            top_words = [feature_names[i] for i in top_words_idx]
            print(f"Topik {idx+1} ({sentiment_label.capitalize()}): {', '.join(top_words)}")

print("\nAnalisis Sentimen menggunakan Topic Modeling (LDA) Selesai.")

"""**Sentimen Negatif — Anatomi Keluhan Publik**

Hasil LDA pada sentimen negatif menghasilkan 5 topik yang secara kolektif membentuk peta keluhan publik yang sangat kaya dan beragam.

**Topik 1** (dolar, bi, indonesia, rakyat, ekonomi, tembus, krisis) mencerminkan narasi **krisis makroekonomi dan akuntabilitas institusi** — publik secara eksplisit mengaitkan pelemahan rupiah dengan kinerja Bank Indonesia (BI) dan kondisi ekonomi nasional secara keseluruhan. Kata "rakyat" dan "krisis" mengindikasikan bahwa keluhan ini bukan sekadar teknis finansial, melainkan sudah menyentuh dimensi keadilan sosial.

**Topik 2** (mbg, prabowo, presiden, perintah, program, rakyat, negara) adalah topik paling mengejutkan sekaligus paling politis di seluruh dataset. Kemunculan "mbg" merujuk pada program **Makan Bergizi Gratis (MBG)** yang dikaitkan langsung oleh publik dengan figur Prabowo selaku presiden. Ini menunjukkan adanya **narasi fiskal yang kuat di kalangan netizen** — sebagian publik secara eksplisit menghubungkan tekanan anggaran dari program-program pemerintah dengan memburuknya nilai tukar rupiah, meski kausalitas ini diperdebatkan secara akademis. Ini adalah sinyal politik yang sangat penting dan tidak bisa diabaikan.

**Topik 3** (harga, impor, minyak, dollar, beli, uang, perang, barang) merepresentasikan **dampak konsumsi langsung** yang paling dirasakan masyarakat sehari-hari — kenaikan harga barang impor, harga minyak yang tertekan oleh dinamika geopolitik ("perang"), dan daya beli yang menurun. Topik ini adalah yang paling dekat dengan kehidupan nyata masyarakat awam.

**Topik 4** (lemah, anjlok, lu, gw, bgt, liat, gue, gin) adalah topik paling informal dan emosional — didominasi bahasa gaul khas Twitter seperti "lu", "gw", "bgt", "gue". Ini merepresentasikan **reaksi emosional spontan** dari publik umum yang merespons kejatuhan rupiah secara personal dan reaktif, bukan analitis.

**Topik 5** (uang, investor, ekonomi, inflasi, asing, pasar) mencerminkan kekhawatiran terhadap **capital outflow dan tekanan pasar keuangan** — narasi yang kemungkinan besar berasal dari pengguna dengan literasi finansial lebih tinggi yang membahas dampak penarikan investor asing dan inflasi sebagai konsekuensi struktural dari pelemahan rupiah.

---

**Sentimen Positif — Narasi Ketahanan dan Peluang**

**Topik 1** (anjlok, lemah, moga, wni) mengandung kata "moga" yang khas — ini adalah ekspresi **harapan dan doa kolektif** dari WNI yang meski mengakui kondisi buruk ("anjlok", "lemah"), tetap merespons dengan optimisme dan semangat. Ini bukan denial, melainkan bentuk resiliensi kultural.

**Topik 2 dan 3** (dolar, harga, juta, miliar, usd, emas, beli, inflasi) menunjukkan narasi strategi finansial dan investasi — kelompok ini membahas pelemahan rupiah bukan sebagai musibah, melainkan sebagai sinyal untuk beralih ke aset safe haven seperti emas atau instrumen berbasis dolar.

**Topik 4** (ekonomi, kuat, global, pasar, inflasi, tumbuh) dan **Topik 5** (ekspor, untung, kuat, beli) secara konsisten memunculkan kata "kuat" dan "ekspor" — merepresentasikan narasi dari **pelaku ekspor dan analis makro** yang melihat sisi positif dari pelemahan rupiah: daya saing ekspor meningkat dan ada peluang keuntungan bagi sektor tertentu.

---

**Sentimen Netral — Ruang Informasi dan Analisis**

**Topik 1** (minyak, iran, ihsg, global) dan **Topik 2** (bunga, suku, pasar, global) menunjukkan bahwa kelompok netral mendominasi wacana **konteks geopolitik dan kebijakan moneter** — membahas konflik Iran, pergerakan IHSG, dan suku bunga sebagai faktor penjelas tanpa muatan emosional. Ini adalah ruang diskusi yang paling edukatif di dataset.

**Topik 3** (emas, bitcoin, btc, aset, miliar) mengungkap adanya sub-komunitas yang membahas **aset kripto dan emas** sebagai instrumen alternatif di tengah ketidakpastian — sebuah tren yang mencerminkan semakin luasnya literasi aset digital di kalangan netizen Indonesia.

**Topik 4 dan 5** (rupiah, nilai, tukar, bi, uang) adalah topik paling "kamus ekonomi" — kemungkinan besar berisi berita, thread edukasi, atau kutipan pernyataan resmi BI tentang pergerakan kurs, tanpa opini atau emosi yang kuat.

### Word Cloud
"""

from wordcloud import WordCloud

sentiments = df_analisis['sentimen'].unique()

for sentiment_label in sentiments:
    if pd.notna(sentiment_label): # Skip NaN sentiments if any
        # Filter DataFrame for the current sentiment
        sentiment_text = df_analisis[df_analisis['sentimen'] == sentiment_label]['text_stemmed'].dropna()

        if not sentiment_text.empty:
            # Combine all cleaned text for the current sentiment
            text_combined = ' '.join(sentiment_text)

            # Generate a word cloud for the current sentiment
            wordcloud = WordCloud(width=800, height=400, background_color='white',
                                  collocations=False).generate(text_combined)

            # Display the generated image
            plt.figure(figsize=(12, 6))
            plt.imshow(wordcloud, interpolation='bilinear')
            plt.axis('off')
            plt.title(f'Word Cloud for {sentiment_label.capitalize()} Sentiment')
            plt.show()
        else:
            print(f"Tidak ada data teks bersih untuk sentimen: {sentiment_label}")

print("Analisis Word Cloud Sentimen Selesai.")

"""**Word Cloud Negatif — Peta Kecemasan Kolektif**

Word cloud sentimen negatif didominasi oleh tiga kata raksasa: **"rupiah"**, **"lemah"**, dan **"anjlok"** — yang secara visual langsung mengkomunikasikan inti keluhan publik tanpa perlu penjelasan tambahan. Di lapisan kedua muncul kata-kata berukuran besar seperti **"harga"**, **"dolar"**, **"ekonomi"**, **"indonesia"**, **"negara"**, **"rakyat"**, **"orang"**, dan** "inflasi"** — membentuk narasi inti bahwa publik memandang pelemahan rupiah sebagai masalah yang menyentuh hajat hidup rakyat dan kedaulatan ekonomi negara secara langsung.

Yang menarik, kata **"perintah"** dan **"prabowo"** muncul dalam ukuran cukup besar di kuadran kiri bawah — mengkonfirmasi temuan Topik 2 LDA bahwa ada narasi kritik politik yang signifikan dalam sentimen negatif, di mana publik mengaitkan kondisi rupiah dengan kebijakan pemerintahan saat ini. Kata "apbn", **"pajak"**, dan **"defisit"** yang turut hadir memperkuat bahwa keluhan publik sudah masuk ke ranah fiskal, bukan sekadar keluhan harga pasar.
Kemunculan kata **"panik"**, **"kabur"**, **"puruk"**, dan **"mahal"** di lapisan berikutnya menangkap dimensi emosional dan ekonomi sehari-hari sekaligus — dari kepanikan psikologis hingga dampak nyata pada daya beli. Sementara kata **"minyak"**, **"impor"**, dan **"perang"** mengkonfirmasi kesadaran publik bahwa tekanan terhadap rupiah tidak terlepas dari faktor geopolitik global.

---
**Word Cloud Positif — Narasi Ketahanan dan Strategi**

Berbeda tajam dari word cloud negatif, sentimen positif menampilkan dominasi kata **"rupiah"**, **"harga"**, **"ekonomi"**, **"lemah"**, dan **"kuat"** secara berdampingan — sebuah kontras yang sangat bermakna. Kata **"kuat"** muncul dalam ukuran besar, menunjukkan bahwa narasi positif bukan sekadar mengabaikan kondisi pelemahan, melainkan secara aktif membangun wacana ketahanan dan kepercayaan diri.
Kata **"beli"**, **"untung"**, **"ekspor"**, **"investasi"**, dan **"emas"** muncul dalam ukuran menengah-besar, mengkonfirmasi temuan LDA bahwa kelompok positif didominasi oleh **narasi peluang finansial** — mereka yang melihat pelemahan rupiah sebagai momen strategis untuk berinvestasi di aset safe haven atau memanfaatkan keunggulan ekspor. Kata **"moga"** yang juga terlihat mencerminkan elemen harapan dan doa kolektif yang khas dari respons budaya Indonesia dalam menghadapi krisis.

Menariknya, kata **"stabil"**, **"tumbuh"**, **"kendali"**, dan **"bijak"** hadir dalam lapisan berikutnya — menunjukkan bahwa sebagian pengguna dalam kategori positif berperan sebagai **penyeimbang narasi**, mengajak publik untuk tetap rasional dan tidak panik berlebihan di tengah gejolak nilai tukar.

---

**Word Cloud Netral — Ruang Diskusi Analitis**

Word cloud netral memiliki karakter paling berbeda dari dua kelompok sebelumnya. Kata **"rupiah"**, **"tembus"**, **"lemah"**, dan **"nilai"** tetap mendominasi, namun yang membedakan adalah kehadiran kuat kata-kata teknis dan kontekstual seperti **"ihsg"**, **"inflasi"**, **"suku"** (bunga), **"investor"**, **"devisa"**, **"pasar"**, **"ekonomi"**, dan **"global"** — menunjukkan bahwa percakapan netral berlangsung pada level analisis yang jauh lebih dalam dan informatif.

Kata **"iran"**, **"trump"**, **"fed"**, **"konflik"**, dan **"geopolitik"** yang muncul di tepian word cloud mengkonfirmasi bahwa kelompok netral memiliki pemahaman kontekstual yang lebih lengkap — mereka menghubungkan pelemahan rupiah dengan dinamika global secara eksplisit, bukan hanya bereaksi pada dampak domestiknya. Kehadiran **"bitcoin"** dan **"saham"** juga menegaskan temuan Topik 3 LDA bahwa ada sub-komunitas investor aset digital yang aktif berdiskusi secara analitis tentang implikasi pelemahan rupiah terhadap portofolio mereka.

### Emotion Analysis
"""

from transformers import pipeline

emotion_model_loaded = False
try:
    # Load the specified emotion analysis model
    emotion_pipeline = pipeline(
        'text-classification',
        model='Aardiiiiy/NusaBERT-base-Indonesian-Plutchik-emotion-analysis',
        tokenizer='Aardiiiiy/NusaBERT-base-Indonesian-Plutchik-emotion-analysis',
        device=0 if torch.cuda.is_available() else -1 # Use GPU if available
    )
    emotion_model_loaded = True
    print("Model emosi berhasil dimuat: Aardiiiiy/NusaBERT-base-Indonesian-Plutchik-emotion-analysis")
except Exception as e:
    print(f"Gagal memuat model emosi: {e}")
    print("Analisis emosi akan dilewati karena masalah otorisasi/akses model atau model tidak ditemukan.")

if emotion_model_loaded:
    # Define a function to get emotion, handling potential NaN values and truncation
    def get_emotion(text):
        if pd.notna(text):
            try:
                # Apply emotion analysis, truncating long texts to prevent errors
                result = emotion_pipeline(text, truncation=True, max_length=512)[0]
                return result['label'], result['score']
            except Exception as e:
                print(f"Error during emotion prediction for text: {text[:50]}... Error: {e}")
                return None, None
        return None, None

    # Apply the function to 'text_stemmed' column and create new 'emosi' and 'skor_emosi' columns
    # Using .loc to avoid SettingWithCopyWarning if df_analisis is a slice
    df_analisis[['emosi', 'skor_emosi']] = df_analisis['text_clean'].apply(lambda x: pd.Series(get_emotion(x)))

    # Tampilkan distribusi emosi
    print("\nDistribusi Emosi:")
    emotion_counts = df_analisis['emosi'].value_counts(dropna=False)
    print(emotion_counts)

    # Visualisasi distribusi emosi
    plt.figure(figsize=(10, 7))
    sns.barplot(x=emotion_counts.index, y=emotion_counts.values, palette='viridis')
    plt.title('Distribusi Emosi')
    plt.xlabel('Emosi')
    plt.ylabel('Jumlah Tweet')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

    print("\nContoh data dengan emosi:")
    display(df_analisis[['text_stemmed', 'emosi', 'skor_emosi']].head())
else:
    print("Kolom 'emosi' dan 'skor_emosi' tidak dibuat karena model gagal dimuat.")

print("\nAnalisis Emosi Selesai.")

"""Hasil analisis emosi menggunakan model Aardiiiiy/NusaBERT-base-Indonesian-Plutchik-emotion-analysis menghasilkan distribusi yang **sangat mengejutkan dan berlawanan dengan asumsi awal.** Dari total 24.910 tweet, distribusi emosi secara berurutan adalah sebagai berikut: **Trust (5.100)**, **Fear (5.050)**, **Anticipation (4.350)**, **Sadness (4.300)**, **Anger (2.300)**, **Surprise (1.950)**, **Disgust (1.150)**, dan **Joy (600)**.

**Trust sebagai emosi terdomian — temuan yang paling tidak terduga**

Fakta bahwa **Trust (kepercayaan)** menempati posisi teratas mengalahkan Fear adalah temuan yang paling kontra-intuitif dalam seluruh riset ini. Di tengah krisis nilai tukar yang mendekati level terlemah sepanjang sejarah, publik Indonesia ternyata masih menyimpan lapisan kepercayaan yang signifikan — kemungkinan besar kepercayaan terhadap kemampuan Bank Indonesia dan pemerintah untuk mengelola krisis, kepercayaan pada fundamental ekonomi Indonesia jangka panjang, atau kepercayaan yang diekspresikan dalam bentuk doa dan harapan kolektif seperti yang tercermin pada word cloud positif ("moga", "stabil", "kendali"). Ini adalah sinyal psikologi sosial yang penting: masyarakat Indonesia mengeluhkan kondisi, tapi belum kehilangan kepercayaan dasarnya pada institusi dan ketahanan ekonomi nasional.

---
**Fear di posisi kedua — kecemasan yang nyata namun terkendali**

Fear (5.050) di posisi kedua mengkonfirmasi bahwa kecemasan adalah emosi dominan kedua dalam percakapan publik tentang pelemahan rupiah. Ketakutan akan kenaikan harga barang impor, naiknya biaya hidup, dan ketidakpastian ekonomi ke depan adalah sumber ketakutan yang paling masuk akal — dan selaras dengan topik-topik LDA yang menonjolkan kata "harga", "impor", "inflasi", dan "krisis". Namun yang patut dicatat adalah selisih Trust dan Fear yang sangat tipis (~50 tweet), menunjukkan bahwa dua emosi yang berlawanan ini hidup berdampingan secara hampir seimbang dalam ruang digital Indonesia.

---
**Anticipation dan Sadness di posisi ketiga dan keempat — publik yang menunggu, bukan yang marah**

Kemunculan **Anticipation** (4.350) sebagai emosi terbesar ketiga adalah temuan yang sangat bermakna secara sosial. Publik Indonesia menghadapi krisis nilai tukar bukan dengan kemarahan yang meledak, melainkan dengan **sikap menunggu dan mengamati** — menantikan langkah kebijakan pemerintah dan BI, menunggu kondisi global membaik, atau mengamati pergerakan kurs sebelum mengambil keputusan finansial. Ini adalah karakter respons yang sangat khas dan mencerminkan pendekatan hati-hati masyarakat dalam menghadapi ketidakpastian ekonomi.

---
**Sadness (4.300)** di posisi keempat, hampir sejajar dengan Anticipation, melengkapi potret ini: publik lebih banyak meratapi kondisi daripada merayakan atau marah. Kesedihan ini kemungkinan besar bersumber dari dampak nyata yang dirasakan sehari-hari — daya beli yang turun, harga kebutuhan yang naik, dan perasaan tidak berdaya menghadapi kondisi makroekonomi yang berada di luar kendali individu.

---
**Anger hanya di posisi kelima — revisi asumsi awal yang signifikan**

Ini adalah koreksi terpenting dari interpretasi sebelumnya. **Anger (2.300) hanya menempati posisi kelima** — jauh di bawah Trust, Fear, Anticipation, dan Sadness. Asumsi awal bahwa kemarahan mendominasi sentimen negatif terbukti **tidak akurat berdasarkan data**. Artinya, percakapan publik tentang pelemahan rupiah di Twitter Indonesia jauh lebih bersifat reflektif, penuh kepercayaan residual, dan dipenuhi antisipasi — bukan ledakan kemarahan kolektif. Ini adalah insight psikologi sosial yang sangat berharga: krisis ekonomi di Indonesia lebih banyak melahirkan pasrah, doa, dan sikap menunggu, bukan konfrontasi terbuka.

**Disgust dan Joy di posisi terbawah**
**Disgust (1.150)** yang relatif rendah menunjukkan bahwa rasa jijik atau kekecewaan mendalam terhadap pemerintah dan BI — meski ada — belum menjadi arus utama percakapan. Sementara **Joy (600)** sebagai emosi paling langka di dataset ini adalah hal yang sangat wajar dalam konteks krisis nilai tukar: hampir tidak ada ruang untuk kegembiraan ketika rupiah mendekati level terlemah sepanjang sejarah.digital.

### 6.5 Interpretasi & Storytelling


- Apa temuan paling menarik dari data?
- Bagaimana hasil analisis sentimen dan metode tambahan saling melengkapi?
- Apa implikasi sosial, ekonomi, budaya, atau politik dari temuan ini?
- Apakah terdapat pola atau anomali yang tidak terduga?

---

**1. Apa Temuan Paling Menarik dari Data?**

Temuan paling menarik dari riset ini bukan terletak pada dominasi sentimen negatif — itu sudah bisa diprediksi ketika rupiah mendekati level terlemah sepanjang sejarah Indonesia. Temuan yang benar-benar mengejutkan ada pada dua hal yang berlawanan dengan asumsi awal.

**Pertama: Trust, bukan Fear atau Anger, yang menjadi emosi paling dominan.**

Hasil emotion analysis menunjukkan bahwa **Trust (5.100 tweet) menempati posisi teratas**, mengalahkan Fear (5.050), Anticipation (4.350), Sadness (4.300), Anger (2.300), Surprise (1.950), Disgust (1.150), dan Joy (600). Ini adalah temuan yang paling kontra-intuitif dalam seluruh riset ini. Di tengah krisis nilai tukar yang mendekati Rp17.900 per dolar AS, publik Indonesia ternyata masih menyimpan lapisan kepercayaan yang signifikan — kepercayaan terhadap kemampuan Bank Indonesia, kepercayaan pada fundamental ekonomi nasional jangka panjang, atau kepercayaan yang diekspresikan dalam bentuk doa dan harapan kolektif. Ini dikonfirmasi pula oleh word cloud positif yang menampilkan kata "moga", "stabil", dan "kendali" secara prominent.

**Kedua: Anger hanya di posisi kelima — jauh lebih rendah dari yang diasumsikan.**

Dengan hanya ~2.300 tweet, Anger kalah jauh dari Trust, Fear, Anticipation, dan Sadness sekaligus. Ini mengoreksi secara fundamental narasi bahwa "masyarakat marah terhadap pemerintah" sebagai respons utama krisis nilai tukar. Yang lebih akurat adalah: publik Indonesia menghadapi krisis ini dengan campuran **kepercayaan residual, kecemasan, antisipasi, dan kesedihan** — bukan dengan amarah yang meledak-ledak. Krisis ekonomi di Indonesia, setidaknya di ruang digital, lebih banyak melahirkan sikap menunggu, berdoa, dan meratap — bukan pemberontakan.

**Ketiga: Narasi fiskal-politik yang muncul organik di sentimen negatif.**

Topik 2 LDA sentimen negatif memunculkan kata-kata "mbg, prabowo, presiden, perintah, program" secara bersamaan — menunjukkan bahwa sebagian publik secara spontan mengaitkan program Makan Bergizi Gratis (MBG) dengan tekanan fiskal yang berkontribusi pada pelemahan rupiah. Ini adalah narasi yang tidak didesain oleh peneliti, melainkan muncul organik dari data, dan menjadikannya temuan orisinal yang paling bernilai dalam riset ini.

---

**2. Bagaimana Semua Metode Saling Melengkapi?**

Keempat metode analisis dalam riset ini bekerja seperti empat lensa kamera dengan focal length berbeda, namun menangkap subjek yang sama: **psikologi kolektif publik Indonesia menghadapi krisis nilai tukar.**

**Analisis Sentimen** memberikan gambaran besar (big picture) — 53,7% negatif, 36,1% netral, 10,2% positif. Angka ini menjawab "apa warna dominan percakapan?" namun belum menjawab "mengapa" dan "seberapa dalam".

**Topic Modeling (LDA)** masuk satu lapisan lebih dalam dan menjawab "apa yang sebenarnya diperbincangkan?". LDA mengungkap bahwa sentimen negatif bukan monolitik — ia terdiri dari setidaknya lima klaster berbeda: kritik institusional terhadap BI, narasi fiskal-politik seputar MBG dan Prabowo, dampak harga barang impor, reaksi emosional spontan, dan kekhawatiran capital outflow. Tanpa LDA, kelima klaster ini akan tenggelam dalam satu label "negatif" yang tidak informatif.

**Word Cloud** mengkomunikasikan temuan secara visual dan intuitif, menjadikannya alat storytelling yang efektif untuk audiens non-teknis. Konfirmasi visual bahwa "prabowo" dan "apbn" muncul di word cloud negatif — bukan hanya di output LDA — memberikan validasi lintas metode yang memperkuat kredibilitas temuan. Di sisi lain, kemunculan "bitcoin" dan "ihsg" di word cloud netral mengkonfirmasi keberadaan komunitas investor yang berdiskusi secara analitis.

**Emotion Analysis** memberikan resolusi tertinggi atas lanskap psikologis publik. Ia tidak hanya menjawab "positif atau negatif?", melainkan "kepercayaan, ketakutan, antisipasi, atau kemarahan?" — dan jawabannya mengejutkan: Trust teratas, Anger hanya kelima. Tanpa lapisan analisis ini, interpretasi akan berhenti pada kesimpulan klise bahwa "publik marah dan takut" — padahal realitanya jauh lebih bernuansa.

Ketika keempat lensa ini dikombinasikan, muncul narasi yang utuh dan akurat: publik Indonesia menghadapi pelemahan rupiah dengan **kepercayaan yang rapuh namun masih ada, kecemasan yang nyata, sikap menunggu yang dominan, dan kesedihan yang dalam** — sementara sebagian kecil mengubah krisis menjadi peluang finansial dan sebagian lainnya menyuarakan kritik fiskal-politik secara organik.

---

**3. Apa Implikasi Sosial, Ekonomi, Budaya, dan Politik dari Temuan Ini?**

**Implikasi Ekonomi: Trust sebagai Aset Kebijakan yang Harus Dijaga**

Temuan bahwa Trust menempati posisi emosi teratas adalah kabar baik sekaligus peringatan bagi otoritas moneter. Kabar baiknya: kepercayaan publik terhadap institusi ekonomi belum runtuh meski rupiah mendekati level historis terlemah. Peringatannya: kepercayaan ini bersifat conditional dan fragile. Data menunjukkan selisih Trust dan Fear hanya ~50 tweet — margin yang sangat tipis. Jika komunikasi kebijakan BI dan pemerintah gagal mengelola ekspektasi publik, konversi dari Trust ke Fear bisa terjadi sangat cepat dan berdampak pada perilaku konsumen, investor, dan pasar secara keseluruhan. Dalam perspektif ekonomi perilaku, trust adalah aset tak berwujud yang pengaruhnya terhadap stabilitas pasar tidak kalah dari intervensi moneter konvensional.

**Implikasi Politik: Narasi MBG-Fiskal sebagai Sinyal Akuntabilitas Publik**

Kemunculan organik kata "mbg", "prabowo", "presiden", dan "apbn" dalam klaster sentimen negatif — dikonfirmasi oleh word cloud negatif yang juga menampilkan "prabowo" dan "apbn" secara eksplisit — adalah sinyal politik yang tidak bisa diabaikan. Publik secara spontan membangun kausalitas antara kebijakan fiskal pemerintahan Prabowo, khususnya program MBG, dengan tekanan terhadap nilai tukar rupiah. Terlepas dari apakah kausalitas ini akurat secara ekonometrik, fakta bahwa narasi ini muncul organik dan masif di media sosial menunjukkan bahwa **persepsi fiskal publik sudah terbentuk** — dan persepsi, dalam konteks pasar keuangan, memiliki kekuatan yang sering kali melebihi fakta itu sendiri.

**Implikasi Sosial: Fragmentasi yang Terstruktur, Bukan Chaos**

Data ini mengungkap bahwa "sentimen publik" bukanlah entitas yang monolitik. Setidaknya terdapat empat segmen sosial yang suaranya berbeda secara struktural dalam dataset: (1) kelompok yang terdampak langsung dan bereaksi emosional singkat — tercermin pada Topik 4 LDA negatif dengan bahasa gaul "lu, gw, bgt"; (2) kelompok analitis-finansial yang merespons dengan strategi investasi — tercermin pada topik emas, dollar, dan bitcoin; (3) kelompok fiskal-politik yang mengaitkan krisis dengan kebijakan pemerintah; dan (4) kelompok resiliensi yang aktif membangun narasi harapan dan kepercayaan. Fragmentasi ini penting karena intervensi komunikasi yang efektif harus dirancang berbeda untuk masing-masing segmen — bukan satu pesan untuk semua.

**Implikasi Budaya: Nrimo Digital sebagai Mekanisme Coping Kolektif**

Dominasi Trust, Anticipation, dan Sadness atas Anger mencerminkan kecenderungan budaya yang dalam. Respons publik Indonesia terhadap krisis ekonomi lebih bersifat menerima daripada konfrontatif. Ini konsisten dengan nilai-nilai budaya Jawa tentang kesabaran dan kepasrahan yang tampaknya tetap terbawa ke ruang digital. Kemunculan kata "moga" di word cloud positif bukan sekadar ekspresi individual — ia adalah manifestasi digital dari mekanisme coping kolektif yang khas Indonesia. Ini adalah temuan antropologis yang menarik: bahkan di era media sosial yang identik dengan kemarahan viral, karakter budaya Indonesia tetap memperlihatkan dirinya dalam distribusi emosi.

---

**4. Apakah Terdapat Pola atau Anomali yang Tidak Terduga?**

**Anomali 1: Trust > Fear dalam konteks krisis nilai tukar**

Secara teoritis, krisis mata uang seharusnya memicu dominasi Fear dan Anger. Namun data menunjukkan sebaliknya — Trust justru tertinggi. Ini adalah anomali yang paling signifikan dan bernilai secara akademis, serta menjadi pembeda utama riset ini dari studi serupa di negara lain.

**Anomali 2: Narasi MBG-Politik muncul organik di sentimen negatif**

Tidak ada satu pun kata kunci scraping yang menargetkan isu MBG atau Prabowo. Namun LDA secara otomatis mengidentifikasi klaster ini sebagai topik yang koheren dan signifikan. Ini menunjukkan bahwa asosiasi publik antara kebijakan pemerintah dan pelemahan rupiah sudah begitu kuat sehingga muncul secara mandiri dalam data tanpa dikonstruksi oleh peneliti.

**Anomali 3: Komunitas kripto aktif di sentimen netral**

Kemunculan "bitcoin", "btc", dan "usd" sebagai klaster tersendiri di LDA netral — dikonfirmasi pula oleh word cloud netral — menunjukkan bahwa komunitas investor aset digital memanfaatkan momen pelemahan rupiah untuk diskusi strategis tentang diversifikasi aset. Ini adalah pola perilaku yang mencerminkan semakin matangnya literasi aset digital di kalangan netizen Indonesia, dan merupakan temuan yang tidak diantisipasi di awal riset.

**Anomali 4: Joy sebagai emosi paling langka (600 tweet)**

Di antara delapan emosi Plutchik, Joy adalah yang paling sedikit — hanya ~600 tweet atau sekitar 2,4% dari total dataset. Ini logis dalam konteks krisis, namun menarik untuk dicatat bahwa bahkan dalam situasi yang secara objektif menguntungkan sebagian pihak (eksportir, penerima remitansi, investor emas dan kripto), ekspresi kegembiraan nyaris tidak muncul di ruang publik digital. Ini bisa mencerminkan norma sosial di Indonesia di mana mengekspresikan keuntungan pribadi di tengah kesulitan orang lain dianggap tidak pantas — atau yang lebih sederhana, kelompok yang diuntungkan memilih ekspresi yang lebih terukur seperti Anticipation daripada Joy yang terbuka.

## BAB 7: Kesimpulan & Rekomendasi

**Kesimpulan**

Riset ini berhasil menjawab ketiga rumusan masalah yang diajukan di BAB 2 dengan menganalisis **24.910 tweet berbahasa Indonesia** selama periode krisis nilai tukar rupiah (9 Maret – 26 Mei 2026), menggunakan kombinasi empat metode: analisis sentimen, topic modeling LDA, word cloud, dan emotion analysis.

**Pertama**, distribusi sentimen publik di platform X menunjukkan dominasi sentimen negatif sebesar **53,7% (13.381 tweet)**, diikuti netral **36,1% (8.996 tweet)**, dan positif **10,2% (2.533 tweet)**. Dominasi negatif ini bukan sekadar drama digital — ia berlandaskan realita empiris di mana rupiah mendekati level terlemah sepanjang sejarah di Rp17.881 per dolar AS, dengan tekanan berlapis dari faktor eksternal (suku bunga The Fed yang higher for longer, eskalasi konflik Iran-AS) dan faktor domestik (capital outflow investor asing dan tekanan fiskal).

**Kedua**, klaster keluhan utama dalam sentimen negatif — sebagaimana diidentifikasi oleh LDA dan dikonfirmasi oleh word cloud — terdiri dari lima topik yang berbeda: (1) kritik institusional terhadap BI dan kondisi ekonomi makro; (2) narasi fiskal-politik yang mengaitkan program MBG dan pemerintahan Prabowo dengan tekanan rupiah; (3) dampak langsung pada harga barang impor dan daya beli masyarakat; (4) reaksi emosional spontan dari publik umum; dan (5) kekhawatiran capital outflow dan tekanan pasar keuangan dari kelompok berliterasi finansial. Dari kelima klaster ini, narasi fiskal-politik (Topik 2) adalah yang paling orisinal karena muncul secara organik tanpa dikonstruksi oleh desain penelitian.

**Ketiga**, karakteristik sentimen positif dan netral jauh lebih kompleks dari sekadar "kontranarasi". Sentimen positif didominasi oleh narasi strategi finansial (investasi emas, aset dolar), ekspresi resiliensi kultural ("moga", "kuat", "stabil"), dan wacana keunggulan ekspor. Sementara sentimen netral adalah ruang diskusi paling analitis — membahas geopolitik (Iran, Trump, Fed), pergerakan IHSG, suku bunga, hingga strategi investasi aset kripto. Keberadaan komunitas kripto sebagai klaster tersendiri di sentimen netral adalah temuan yang mencerminkan semakin matangnya literasi aset digital di kalangan netizen Indonesia.

**Keempat — dan ini adalah temuan terpenting yang melampaui rumusan masalah awal** — emotion analysis mengungkap bahwa **Trust (5.100) adalah emosi paling dominan**, mengalahkan Fear (5.050), Anticipation (4.350), Sadness (4.300), dan Anger (2.300). Temuan ini mengoreksi secara fundamental asumsi bahwa kemarahan mendominasi respons publik terhadap krisis nilai tukar. Realitanya, masyarakat Indonesia menghadapi krisis ini dengan kepercayaan residual yang masih ada, kecemasan yang nyata namun berdampingan dengan harapan, dan sikap menunggu yang jauh lebih dominan dari amarah. Ini adalah potret psikologi sosial yang khas dan bernilai tinggi bagi siapa pun yang ingin memahami atau merespons dinamika opini publik di Indonesia.

---
**Rekomendasi**

**Untuk Bank Indonesia dan Pemerintah:**
Temuan bahwa Trust masih menempati posisi tertinggi adalah modal besar yang harus dikelola dengan sangat hati-hati. Selisih Trust dan Fear yang hanya ~50 tweet menunjukkan betapa rentannya kepercayaan ini. Rekomendasi konkretnya: jadikan social listening berbasis NLP sebagai bagian permanen dari sistem manajemen krisis — bukan hanya dipantau secara ad hoc. Lonjakan sentimen negatif dan pergeseran Trust ke Fear yang terdeteksi secara real-time di media sosial dapat menjadi early warning system yang lebih cepat dari survei kepercayaan konsumen konvensional. Komunikasi kebijakan yang empatik, transparan, dan responsif terhadap narasi yang beredar di publik — termasuk narasi fiskal-politik seputar MBG — adalah kunci untuk mempertahankan kepercayaan yang saat ini masih ada.

**Untuk Peneliti Selanjutnya:**
Riset ini dapat dikembangkan ke tiga arah yang paling menjanjikan. Pertama, analisis cross-platform yang membandingkan sentimen di X, Instagram, dan TikTok untuk melihat apakah karakter emosional yang berbeda muncul di platform yang berbeda. Kedua, analisis time-series yang menghubungkan lonjakan volume tweet dan pergeseran distribusi emosi harian dengan pergerakan kurs aktual — untuk menguji apakah sentimen digital berfungsi sebagai leading indicator atau lagging indicator pergerakan rupiah. Ketiga, riset lanjutan yang secara spesifik membedah klaster narasi fiskal-politik (MBG-Prabowo) menggunakan metode analisis wacana (discourse analysis) untuk memahami lebih dalam bagaimana publik mengkonstruksi kausalitas antara kebijakan fiskal dan nilai tukar.

**Untuk Tim Internal BeData:**
Riset ini membuktikan bahwa kombinasi empat metode — sentiment analysis, LDA, word cloud, dan emotion analysis berbasis Plutchik — menghasilkan pemahaman yang jauh lebih kaya dibanding analisis sentimen tunggal. Model pipeline ini dapat direplikasi sebagai produk social listening berkelanjutan untuk klien korporat (memantau sentimen terhadap brand di tengah krisis ekonomi) maupun lembaga pemerintah (mengukur kepercayaan publik terhadap kebijakan secara real-time). Temuan bahwa Trust adalah emosi dominan bahkan di tengah krisis juga membuka peluang narasi yang lebih nuansatif dalam laporan-laporan riset BeData ke depan — melampaui dikotomi sederhana "publik puas vs tidak puas".

---
*Disusun berdasarkan analisis data tweet periode 9 Maret – 26 Mei 2026. Seluruh interpretasi dalam google colab ini didasarkan pada output aktual yang terverifikasi: distribusi sentimen (negative: 13.381, neutral: 8.996, positive: 2.533), output LDA per klaster sentimen, visualisasi word cloud, dan distribusi emosi Plutchik (Trust: ~5.100, Fear: ~5.050, Anticipation: ~4.350, Sadness: ~4.300, Anger: ~2.300, Surprise: ~1.950, Disgust: ~1.150, Joy: ~600).*
"""